CREATE TABLE Bank (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nama VARCHAR(255),
  kode VARCHAR(10),
  alamat VARCHAR(255)
);

-- --------------------------------------------------------

CREATE TABLE kota (
  id INT AUTO_INCREMENT PRIMARY KEY,
  kota varchar(255) not null ,
  provinsi varchar(255) not null,
  CONSTRAINT kota_na UNIQUE (kota)
);

-- --------------------------------------------------------

CREATE TABLE coa (
  id int AUTO_INCREMENT PRIMARY KEY,
  kode INT NOT NULL,
  created_at datetime DEFAULT current_timestamp()
);

-- --------------------------------------------------------

CREATE TABLE users (
  id int AUTO_INCREMENT PRIMARY KEY,
  username varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  phone varchar(255) DEFAULT NULL,
  otp varchar(255) DEFAULT '00',
  password varchar(255) DEFAULT '00',
  store_token varchar(255) DEFAULT NULL,
  reset_token varchar(255) DEFAULT NULL,
  role int NOT NULL DEFAULT 0,
  status int NOT NULL DEFAULT 1,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_otp_reset datetime DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp()
);

-- --------------------------------------------------------

CREATE TABLE nasabah (
  id int AUTO_INCREMENT PRIMARY KEY,
  id_user INT NOT NULL,
  id_validator INT NOT NULL,
  nama varchar(255) NOT NULL,
  ktp int DEFAULT NULL,
  image_ktp varchar(255) DEFAULT NULL,
  image_selfie varchar(255) DEFAULT NULL,
  tmpt_lahir varchar(255) DEFAULT NULL,
  tgl_lahir date DEFAULT NULL,
  ibu_kandung varchar(255) DEFAULT NULL,
  id_privy varchar(255) default null,
  id_bank int DEFAULT NULL,
  norek varchar(255) DEFAULT NULL,
  status_pernikahan int default null,
  alamat varchar(255) DEFAULT NULL,
  jenis_pekerjaan int default null,
  alamat_kerja varchar(255) DEFAULT NULL,
  penghasilan int default null,
  nama_ahli_waris varchar(255) DEFAULT NULL,
  ktp_ahli_waris INT DEFAULT NULL,
  image_ktp_ahli_waris varchar(255) DEFAULT NULL,
  hub_ahli_waris INT DEFAULT NULL,
  phone_ahli_waris varchar(255) DEFAULT NULL,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  validasi int DEFAULT 0, -- 1=Blm Valid, 2=Sdh Valid
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_nasabah_bank FOREIGN KEY (id_bank) REFERENCES bank(id),
  CONSTRAINT fk_nasabah_user FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT fk_nasabah_validator FOREIGN KEY (id_validator) REFERENCES users(id)
);

-- --------------------------------------------------------

CREATE TABLE mitra (
  id int AUTO_INCREMENT PRIMARY KEY,
  nama varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  kode_bank varchar(255) not NULL,
  no_npwp varchar(255) not NULL,
  no_akta_pendirian varchar(255) not NULL,
  tgl_pendirian date default NULL,
  no_pengesahan_akta varchar(255) default NULL,
  tgl_pengesahan_akta date not NULL,
  nama_notaris varchar(255) default NULL,
  lokasi_notaris varchar(255) default NULL,
  no_ijin varchar(255) default NULL,
  tgl_ijin date default NULL,
  provinsi int default NULL,
  kota int default NULL,
  alamat varchar(255) default NULL,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  npwp_provinsi int default NULL,
  npwp_kota int default NULL,
  npwp_alamat varchar(255) default NULL,
  phone varchar(255) DEFAULT NULL,
  website varchar(255) DEFAULT NULL,
  mulai_beroperasi date DEFAULT NULL,
  nama_pengurus varchar(255) default null,
  jabatan_pengurus varchar(255) default null,
  phone_pengurus varchar(255) default null,
  id_bank int default null,
  norek_bank varchar(255) default null,
  id_privy varchar(255) default null,
  logo varchar(255) default null,
  validasi int default 0,
  id_validator INT NOT NULL,
  keterangan varchar(255) default null,
  db_name varchar(255) NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_mitra_validator FOREIGN KEY (id_validator) REFERENCES users(id),
  CONSTRAINT fk_mitra_bank FOREIGN KEY (id_bank) REFERENCES bank(id)
);

-- --------------------------------------------------------

CREATE TABLE norek_mitra (
  id int AUTO_INCREMENT PRIMARY KEY,
  id_mitra int not null,
  id_bank int not null,
  atas_nama varchar(255) not null,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_norekmitra_bank FOREIGN KEY (id_bank) REFERENCES bank(id),
  CONSTRAINT fk_norekmitra_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE admin_bpr (
  id int AUTO_INCREMENT PRIMARY KEY,
  id_user INT NOT NULL,
  id_mitra INT DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_admin_user FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT fk_admin_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE neraca (
  id int AUTO_INCREMENT PRIMARY KEY,
  id_mitra INT NOT NULL,
  asset INT DEFAULT 0,
  kewajiban INT DEFAULT 0,
  ekuitas INT DEFAULT 0,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_neraca_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE produk (
  id int AUTO_INCREMENT PRIMARY KEY,
  id_mitra INT NOT NULL,
  no_produk varchar(255) NOT NULL,
  minimal int default null,
  target int default null,
  komisi int default null,
  tenor int default null,
  start_date date DEFAULT null,
  end_date date DEFAULT null,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_at datetime DEFAULT current_timestamp(),
  updated_at datetime DEFAULT NULL ON UPDATE current_timestamp(),
  CONSTRAINT fk_produk_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE log_app (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_user int not null,
  keterangan varchar(255) not null,
  notifikasi int default 0,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_at datetime DEFAULT current_timestamp(),
  CONSTRAINT fk_logapp_user FOREIGN KEY (id_user) REFERENCES users(id)
);

-- --------------------------------------------------------

INSERT INTO kota (provinsi, kota) VALUES
  ('Aceh', 'Banda Aceh'),
  ('Aceh', 'Sabang'),
  ('Aceh', 'Lhokseumawe'),
  ('Aceh', 'Langsa'),
  ('Aceh', 'Meulaboh'),
  ('Bali', 'Denpasar'),
  ('Bali', 'Singaraja'),
  ('Bali', 'Tabanan'),
  ('Bali', 'Gianyar'),
  ('Bali', 'Badung'),
  ('Banten', 'Serang'),
  ('Banten', 'Tangerang'),
  ('Banten', 'Cilegon'),
  ('Banten', 'Tangerang Selatan'),
  ('Bengkulu', 'Bengkulu'),
  ('Bengkulu', 'Curup'),
  ('Bengkulu', 'Muko-Muko'),
  ('Bengkulu', 'Manna'),
  ('Bengkulu', 'Kaur'),
  ('Gorontalo', 'Gorontalo'),
  ('Gorontalo', 'Limboto'),
  ('Gorontalo', 'Tilamuta'),
  ('Gorontalo', 'Kwandang'),
  ('Gorontalo', 'Suwawa'),
  ('Jakarta', 'Jakarta Pusat'),
  ('Jakarta', 'Jakarta Barat'),
  ('Jakarta', 'Jakarta Timur'),
  ('Jakarta', 'Jakarta Utara'),
  ('Jakarta', 'Jakarta Selatan'),
  ('Jambi', 'Jambi'),
  ('Jambi', 'Sungai Penuh'),
  ('Jambi', 'Sarolangun'),
  ('Jambi', 'Muara Bulian'),
  ('Jambi', 'Tebo'),
  ('Jawa Barat', 'Bandung'),
  ('Jawa Barat', 'Bekasi'),
  ('Jawa Barat', 'Bogor'),
  ('Jawa Barat', 'Depok'),
  ('Jawa Barat', 'Cimahi'),
  ('Jawa Tengah', 'Semarang'),
  ('Jawa Tengah', 'Surakarta'),
  ('Jawa Tengah', 'Salatiga'),
  ('Jawa Tengah', 'Magelang'),
  ('Jawa Tengah', 'Pekalongan'),
  ('Jawa Timur', 'Surabaya'),
  ('Jawa Timur', 'Malang'),
  ('Jawa Timur', 'Sidoarjo'),
  ('Jawa Timur', 'Jember'),
  ('Jawa Timur', 'Mojokerto'),
  ('Kalimantan Barat', 'Pontianak'),
  ('Kalimantan Barat', 'Singkawang'),
  ('Kalimantan Barat', 'Kubu Raya'),
  ('Kalimantan Barat', 'Sambas'),
  ('Kalimantan Selatan', 'Banjarmasin'),
  ('Kalimantan Selatan', 'Banjarbaru'),
  ('Kalimantan Selatan', 'Martapura'),
  ('Kalimantan Selatan', 'Tanjung'),
  ('Kalimantan Tengah', 'Palangkaraya'),
  ('Kalimantan Tengah', 'Sampit'),
  ('Kalimantan Tengah', 'Kuala Pembuang'),
  ('Kalimantan Tengah', 'Buntok'),
  ('Kalimantan Timur', 'Samarinda'),
  ('Kalimantan Timur', 'Balikpapan'),
  ('Kalimantan Timur', 'Bontang'),
  ('Kalimantan Timur', 'Tarakan'),
  ('Kalimantan Timur', 'Sangatta'),
  ('Kalimantan Utara', 'Tanjung Selor'),
  ('Kalimantan Utara', 'Bulungan'),
  ('Kalimantan Utara', 'Malinau'),
  ('Kepulauan Bangka', 'Belitung	Pangkal Pinang'),
  ('Kepulauan Bangka', 'Sungailiat'),
  ('Kepulauan Bangka', 'Muntok'),
  ('Kepulauan Bangka', 'Toboali'),
  ('Kepulauan Bangka', 'Manggar'),
  ('Kepulauan Riau', 'Tanjung Pinang'),
  ('Kepulauan Riau', 'Batam'),
  ('Kepulauan Riau', 'Bintan'),
  ('Kepulauan Riau', 'Karimun'),
  ('Lampung	Bandar', 'Lampung'),
  ('Lampung	Bandar', 'Metro'),
  ('Lampung	Bandar', 'Krui'),
  ('Lampung	Bandar', 'Liwa'),
  ('Lampung	Bandar', 'Kotabumi'),
  ('Maluku Utara', 'Ternate'),
  ('Maluku Utara', 'Tidore'),
  ('Maluku Utara', 'Kepulauan'),
  ('Maluku Utara', 'Sofifi'),
  ('Maluku Utara', 'Jailolo'),
  ('Papua Barat', 'Manokwari'),
  ('Papua Barat', 'Sorong'),
  ('Papua Barat', 'Fakfak'),
  ('Papua Barat', 'Kaimana'),
  ('Papua Barat', 'Teminabuan'),
  ('Maluku',	'Ambon'),
  ('Maluku', 'Tual'),
  ('Maluku', 'Masohi'),
  ('Maluku', 'Namlea'),
  ('Maluku', 'Saumlaki'),
  ('Yogyakarta',	'Yogyakarta'),
  ('Yogyakarta', 'Bantul'),
  ('Yogyakarta', 'Sleman'),
  ('Yogyakarta', 'Gunungkidul'),
  ('Yogyakarta', 'Kulon'),
  ('Yogyakarta', 'Progo'),
  ('Riau', 'Pekanbaru'),
  ('Riau', 'Dumai'),
  ('Riau', 'Bengkalis'),
  ('Riau', 'Siak'),
  ('Riau', 'Tembilahan'),
  ('Papua', 'Jayapura'),
  ('Papua', 'Timika'),
  ('Papua', 'Merauke'),
  ('Papua', 'Biak'),
  ('Papua', 'Nabire'),
  ('Nusa Tenggara Barat',	'Mataram'),
  ('Nusa Tenggara Barat',	'Bima'),
  ('Nusa Tenggara Barat', 'Praya'),
  ('Nusa Tenggara Barat',	'Selong'),
  ('Nusa Tenggara Barat',	'Gerung'),
  ('Nusa Tenggara Timur',	'Kupang'),
  ('Nusa Tenggara Timur',	'Ende'),
  ('Nusa Tenggara Timur', 'Maumere'),
  ('Nusa Tenggara Timur',	'Ruteng'),
  ('Nusa Tenggara Timur',	'Soe'),
  ('Sulawesi Barat', 'Mamuju'),
  ('Sulawesi Barat', 'Polewali Mandar'),
  ('Sulawesi Barat', 'Majene'),
  ('Sulawesi Barat', 'Mamasa'),
  ('Sulawesi Selatan', 'Makassar'),
  ('Sulawesi Selatan', 'Parepare'),
  ('Sulawesi Selatan', 'Kendari'),
  ('Sulawesi Selatan', 'Palopo'),
  ('Sulawesi Tengah', 'Palu'),
  ('Sulawesi Tengah', 'Poso'),
  ('Sulawesi Tengah', 'Donggala'),
  ('Sulawesi Tengah', 'Parigi Moutong'),
  ('Sulawesi Tenggara', 'Bau-Bau'),
  ('Sulawesi Tenggara', 'Raha'),
  ('Sulawesi Tenggara', 'Lasusua'),
  ('Sulawesi Utara', 'Manado'),
  ('Sulawesi Utara', 'Bitung'),
  ('Sulawesi Utara', 'Tomohon'),
  ('Sulawesi Utara', 'Kotamobagu'),
  ('Sulawesi Utara', 'Airmadidi'),
  ('Sumatera Barat', 'Padang'),
  ('Sumatera Barat', 'Bukittinggi'),
  ('Sumatera Barat', 'Payakumbuh'),
  ('Sumatera Barat', 'Pariaman'),
  ('Sumatera Barat', 'Solok'),
  ('Sumatera Selatan', 'Palembang'),
  ('Sumatera Selatan', 'Prabumulih'),
  ('Sumatera Selatan', 'Lubuklinggau'),
  ('Sumatera Selatan', 'Lahat'),
  ('Sumatera Selatan', 'Pagar Alam'),
  ('Sumatera Utara', 'Medan'),
  ('Sumatera Utara', 'Binjai'),
  ('Sumatera Utara', 'Pematangsiantar'),
  ('Sumatera Utara', 'Tebing Tinggi'),
  ('Sumatera Utara', 'Tanjung Balai')
;
