CREATE TABLE bank (
  id INT IDENTITY(1,1) PRIMARY KEY,
  nama VARCHAR(255),
  kode VARCHAR(10),
  alamat VARCHAR(255)
);

-- --------------------------------------------------------

CREATE TABLE kota (
  id INT IDENTITY(1,1) PRIMARY KEY,
  kota nvarchar(255) not null,
  provinsi nvarchar(255) not null,
  CONSTRAINT kota_na UNIQUE (kota)
);

-- --------------------------------------------------------

CREATE TABLE coa (
  id int IDENTITY(1,1) PRIMARY KEY,
  kode nvarchar(10) NOT NULL,
  CONSTRAINT kode_na UNIQUE (kode)
);

-- --------------------------------------------------------

CREATE TABLE users (
  id int IDENTITY(1,1) PRIMARY KEY,
  username varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  phone varchar(255) DEFAULT NULL,
  [otp] varchar(255) DEFAULT Null,
  [password] varchar(255) DEFAULT Null,
  store_token text DEFAULT NULL,
  reset_token text DEFAULT NULL,
  [role] int NOT NULL DEFAULT 0,
  [status] int NOT NULL DEFAULT 0,
  kriptorone varchar(255) default NULL,
  kriptortwo varchar(255) default NULL,
  created_otp datetime DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_at datetime DEFAULT NULL
);

-- --------------------------------------------------------

CREATE TABLE nasabah (
  id int IDENTITY(1,1) PRIMARY KEY,
  id_user INT NOT NULL,
  id_validator INT default NULL,
  nama varchar(255) default NULL,
  ktp varchar(255) DEFAULT NULL,
  image_ktp varchar(255) DEFAULT NULL,
  image_selfie varchar(255) DEFAULT NULL,
  tmpt_lahir varchar(255) DEFAULT NULL,
  tgl_lahir varchar(255) DEFAULT NULL,
  ibu_kandung varchar(255) DEFAULT NULL,
  id_privy nvarchar(255) NULL,
  id_bank int DEFAULT NULL,
  norek varchar(255) DEFAULT NULL,
  status_pernikahan int NULL,
  jenis_pekerjaan int NULL,
  alamat varchar(255) DEFAULT NULL,
  alamat_kerja varchar(255) DEFAULT NULL,
  penghasilan int NULL,
  nama_ahli_waris varchar(255) DEFAULT NULL,
  ktp_ahli_waris varchar(255) DEFAULT NULL,
  image_ktp_ahli_waris varchar(255) DEFAULT NULL,
  hub_ahli_waris varchar(255) DEFAULT NULL,
  phone_ahli_waris varchar(255) DEFAULT NULL,
  validasi int DEFAULT NULL, -- 1=Blm Valid, 2=Sdh Valid
  created_at datetime DEFAULT current_timestamp,
  updated_at datetime DEFAULT NULL,
  CONSTRAINT fk_nasabah_user FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT fk_nasabah_bank FOREIGN KEY (id_bank) REFERENCES bank(id),
  CONSTRAINT fk_nasabah_validator FOREIGN KEY (id_validator) REFERENCES users(id)
);

-- --------------------------------------------------------

CREATE TABLE mitra (
  id int IDENTITY(1,1) PRIMARY KEY,
  id_user INT NOT NULL,
  nama nvarchar(255) NOT NULL,
  kode_bank int default NULL,
  no_npwp nvarchar(255) default NULL,
  no_akta_pendirian nvarchar(255) default NULL,
  tgl_pendirian date default NULL,
  no_pengesahan_akta nvarchar(255) default NULL,
  tgl_pengesahan_akta date default NULL,
  nama_notaris nvarchar(255) default NULL,
  lokasi_notaris nvarchar(255) default NULL,
  no_ijin nvarchar(255) default NULL,
  tgl_ijin date default NULL,
  kota int NULL,
  alamat nvarchar(255) default NULL,
  npwp_provinsi nvarchar(255) default NULL,
  npwp_kota nvarchar(255) default NULL,
  npwp_alamat nvarchar(255) default NULL,
  website nvarchar(255) default NULL,
  mulai_beroperasi date default NULL,
  nama_pengurus nvarchar(255) default NULL,
  jabatan_pengurus nvarchar(255) default NULL,
  phone_pengurus nvarchar(255) default NULL,
  id_bank int default NULL,
  norek_bank nvarchar(255) default NULL,
  id_privy nvarchar(255) default NULL,
  logo nvarchar(255) default NULL,
  validasi int DEFAULT 0,
  id_validator INT NOT NULL,
  keterangan nvarchar(255) default null,
  db_name nvarchar(255)  default NULL,
  created_at datetime DEFAULT GETDATE(),
  updated_at datetime DEFAULT NULL,
  CONSTRAINT fk_mitra_user FOREIGN KEY (id_user) REFERENCES users(id),
  CONSTRAINT fk_mitra_bank FOREIGN KEY (id_bank) REFERENCES bank(id),
  CONSTRAINT fk_mitra_validator FOREIGN KEY (id_validator) REFERENCES users(id)
);

-- --------------------------------------------------------

CREATE TABLE norek_mitra (
  id int IDENTITY(1,1) PRIMARY KEY,
  id_mitra int not null,
  id_bank int not null,
  atas_nama varchar(255) not null,
  created_at datetime DEFAULT current_timestamp,
  updated_at datetime DEFAULT NULL,
  CONSTRAINT fk_norekmitra_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id),
  CONSTRAINT fk_norekmitra_bank FOREIGN KEY (id_bank) REFERENCES bank(id)
);

-- --------------------------------------------------------

CREATE TABLE neraca (
  id int IDENTITY(1,1) PRIMARY KEY,
  id_mitra INT NOT NULL,
  asset INT DEFAULT 0,
  kewajiban INT DEFAULT 0,
  ekuitas INT DEFAULT 0,
  created_at datetime DEFAULT GETDATE(),
  updated_at datetime DEFAULT NULL,
  CONSTRAINT fk_neraca_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE produk (
  id int IDENTITY(1,1) PRIMARY KEY,
  id_mitra INT NOT NULL,
  no_produk nvarchar(255) NOT NULL,
  minimal nvarchar(255) NULL,
  target nvarchar(255) NULL,
  bagi_hasil nvarchar(255) NULL,
  tenor nvarchar(255) NULL,
  start_date date NULL,
  end_date date NULL,
  created_at datetime DEFAULT GETDATE(),
  updated_at datetime DEFAULT NULL,
  CONSTRAINT fk_produk_mitra FOREIGN KEY (id_mitra) REFERENCES mitra(id)
);

-- --------------------------------------------------------

CREATE TABLE log_app (
  id INT IDENTITY(1,1) PRIMARY KEY,
  id_user int not null,
  keterangan text not null,
  notifikasi int DEFAULT 0,
  created_at datetime DEFAULT GETDATE(),
  CONSTRAINT fk_logapp_user FOREIGN KEY (id_user) REFERENCES users(id)
);

-- --------------------------------------------------------

INSERT INTO kota (provinsi, kota) VALUES
  ('Aceh', 'Banda Aceh'),
  ('Aceh', 'Sabang'),
  ('Aceh', 'Lhokseumawe'),
  ('Aceh', 'Langsa'),
  ('Aceh', 'Meulaboh'),
  ('Bali', 'Denpasar'),
  ('Bali', 'Singaraja'),
  ('Bali', 'Tabanan'),
  ('Bali', 'Gianyar'),
  ('Bali', 'Badung'),
  ('Banten', 'Serang'),
  ('Banten', 'Tangerang'),
  ('Banten', 'Cilegon'),
  ('Banten', 'Tangerang Selatan'),
  ('Bengkulu', 'Bengkulu'),
  ('Bengkulu', 'Curup'),
  ('Bengkulu', 'Muko-Muko'),
  ('Bengkulu', 'Manna'),
  ('Bengkulu', 'Kaur'),
  ('Gorontalo', 'Gorontalo'),
  ('Gorontalo', 'Limboto'),
  ('Gorontalo', 'Tilamuta'),
  ('Gorontalo', 'Kwandang'),
  ('Gorontalo', 'Suwawa'),
  ('Jakarta', 'Jakarta Pusat'),
  ('Jakarta', 'Jakarta Barat'),
  ('Jakarta', 'Jakarta Timur'),
  ('Jakarta', 'Jakarta Utara'),
  ('Jakarta', 'Jakarta Selatan'),
  ('Jambi', 'Jambi'),
  ('Jambi', 'Sungai Penuh'),
  ('Jambi', 'Sarolangun'),
  ('Jambi', 'Muara Bulian'),
  ('Jambi', 'Tebo'),
  ('Jawa Barat', 'Bandung'),
  ('Jawa Barat', 'Bekasi'),
  ('Jawa Barat', 'Bogor'),
  ('Jawa Barat', 'Depok'),
  ('Jawa Barat', 'Cimahi'),
  ('Jawa Tengah', 'Semarang'),
  ('Jawa Tengah', 'Surakarta'),
  ('Jawa Tengah', 'Salatiga'),
  ('Jawa Tengah', 'Magelang'),
  ('Jawa Tengah', 'Pekalongan'),
  ('Jawa Timur', 'Surabaya'),
  ('Jawa Timur', 'Malang'),
  ('Jawa Timur', 'Sidoarjo'),
  ('Jawa Timur', 'Jember'),
  ('Jawa Timur', 'Mojokerto'),
  ('Kalimantan Barat', 'Pontianak'),
  ('Kalimantan Barat', 'Singkawang'),
  ('Kalimantan Barat', 'Kubu Raya'),
  ('Kalimantan Barat', 'Sambas'),
  ('Kalimantan Selatan', 'Banjarmasin'),
  ('Kalimantan Selatan', 'Banjarbaru'),
  ('Kalimantan Selatan', 'Martapura'),
  ('Kalimantan Selatan', 'Tanjung'),
  ('Kalimantan Tengah', 'Palangkaraya'),
  ('Kalimantan Tengah', 'Sampit'),
  ('Kalimantan Tengah', 'Kuala Pembuang'),
  ('Kalimantan Tengah', 'Buntok'),
  ('Kalimantan Timur', 'Samarinda'),
  ('Kalimantan Timur', 'Balikpapan'),
  ('Kalimantan Timur', 'Bontang'),
  ('Kalimantan Timur', 'Tarakan'),
  ('Kalimantan Timur', 'Sangatta'),
  ('Kalimantan Utara', 'Tanjung Selor'),
  ('Kalimantan Utara', 'Bulungan'),
  ('Kalimantan Utara', 'Malinau'),
  ('Kepulauan Bangka', 'Belitung	Pangkal Pinang'),
  ('Kepulauan Bangka', 'Sungailiat'),
  ('Kepulauan Bangka', 'Muntok'),
  ('Kepulauan Bangka', 'Toboali'),
  ('Kepulauan Bangka', 'Manggar'),
  ('Kepulauan Riau', 'Tanjung Pinang'),
  ('Kepulauan Riau', 'Batam'),
  ('Kepulauan Riau', 'Bintan'),
  ('Kepulauan Riau', 'Karimun'),
  ('Lampung	Bandar', 'Lampung'),
  ('Lampung	Bandar', 'Metro'),
  ('Lampung	Bandar', 'Krui'),
  ('Lampung	Bandar', 'Liwa'),
  ('Lampung	Bandar', 'Kotabumi'),
  ('Maluku Utara', 'Ternate'),
  ('Maluku Utara', 'Tidore'),
  ('Maluku Utara', 'Kepulauan'),
  ('Maluku Utara', 'Sofifi'),
  ('Maluku Utara', 'Jailolo'),
  ('Papua Barat', 'Manokwari'),
  ('Papua Barat', 'Sorong'),
  ('Papua Barat', 'Fakfak'),
  ('Papua Barat', 'Kaimana'),
  ('Papua Barat', 'Teminabuan'),
  ('Maluku',	'Ambon'),
  ('Maluku', 'Tual'),
  ('Maluku', 'Masohi'),
  ('Maluku', 'Namlea'),
  ('Maluku', 'Saumlaki'),
  ('Yogyakarta',	'Yogyakarta'),
  ('Yogyakarta', 'Bantul'),
  ('Yogyakarta', 'Sleman'),
  ('Yogyakarta', 'Gunungkidul'),
  ('Yogyakarta', 'Kulon'),
  ('Yogyakarta', 'Progo'),
  ('Riau', 'Pekanbaru'),
  ('Riau', 'Dumai'),
  ('Riau', 'Bengkalis'),
  ('Riau', 'Siak'),
  ('Riau', 'Tembilahan'),
  ('Papua', 'Jayapura'),
  ('Papua', 'Timika'),
  ('Papua', 'Merauke'),
  ('Papua', 'Biak'),
  ('Papua', 'Nabire'),
  ('Nusa Tenggara Barat', 'Mataram'),
  ('Nusa Tenggara Barat', 'Bima'),
  ('Nusa Tenggara Barat', 'Praya'),
  ('Nusa Tenggara Barat', 'Selong'),
  ('Nusa Tenggara Barat', 'Gerung'),
  ('Nusa Tenggara Timur', 'Kupang'),
  ('Nusa Tenggara Timur', 'Ende'),
  ('Nusa Tenggara Timur', 'Maumere'),
  ('Nusa Tenggara Timur', 'Ruteng'),
  ('Nusa Tenggara Timur', 'Soe'),
  ('Sulawesi Barat', 'Mamuju'),
  ('Sulawesi Barat', 'Polewali Mandar'),
  ('Sulawesi Barat', 'Majene'),
  ('Sulawesi Barat', 'Mamasa'),
  ('Sulawesi Selatan', 'Makassar'),
  ('Sulawesi Selatan', 'Parepare'),
  ('Sulawesi Selatan', 'Kendari'),
  ('Sulawesi Selatan', 'Palopo'),
  ('Sulawesi Tengah', 'Palu'),
  ('Sulawesi Tengah', 'Poso'),
  ('Sulawesi Tengah', 'Donggala'),
  ('Sulawesi Tengah', 'Parigi Moutong'),
  ('Sulawesi Tenggara', 'Bau-Bau'),
  ('Sulawesi Tenggara', 'Raha'),
  ('Sulawesi Tenggara', 'Lasusua'),
  ('Sulawesi Utara', 'Manado'),
  ('Sulawesi Utara', 'Bitung'),
  ('Sulawesi Utara', 'Tomohon'),
  ('Sulawesi Utara', 'Kotamobagu'),
  ('Sulawesi Utara', 'Airmadidi'),
  ('Sumatera Barat', 'Padang'),
  ('Sumatera Barat', 'Bukittinggi'),
  ('Sumatera Barat', 'Payakumbuh'),
  ('Sumatera Barat', 'Pariaman'),
  ('Sumatera Barat', 'Solok'),
  ('Sumatera Selatan', 'Palembang'),
  ('Sumatera Selatan', 'Prabumulih'),
  ('Sumatera Selatan', 'Lubuklinggau'),
  ('Sumatera Selatan', 'Lahat'),
  ('Sumatera Selatan', 'Pagar Alam'),
  ('Sumatera Utara', 'Medan'),
  ('Sumatera Utara', 'Binjai'),
  ('Sumatera Utara', 'Pematangsiantar'),
  ('Sumatera Utara', 'Tebing Tinggi'),
  ('Sumatera Utara', 'Tanjung Balai')
;
